bookforum/urls.py
from django.urls import path
from bookforum.views import *

app_name = 'bookforum'

urlpatterns = [
    path('', show_forum, name='show_forum' ),
    path('create_question/', create_question, name='create_question'),
    path('create_question_flutter/', create_question_flutter, name='create_question_flutter'),
    path('create_comments/<int:pk>', create_comments, name="create_comments"),
    path('create_comments_flutter/<int:pk>', create_comments_flutter, name="create_comments_flutter"),
    path('delete_question/<str:username>/<int:id>', delete_question, name="delete_question"),
    path('delete_question_flutter/<str:username>/<int:id>', delete_question_flutter, name="delete_question"),
    path('delete_comments/<str:username>/<int:id>', delete_comments, name="delete_comments"),
    path('delete_comments_flutter/<str:username>/<int:id>', delete_comments_flutter, name="delete_comments_flutter"),
    path('uniquecomments/json/<int:id>', show_uniquecomments_json, name="show_uniquecomments_json"),
    path('show_books_json/json/', show_books_json, name="show_books_json"),
    path('forum/json2/', show_forum_json_2, name="show_forum_json_2"),
    path('show_forumcomments/<int:id_head>/', show_forumcomments, name="show_forumcomments"),
    path('forum/json/', show_forum_json, name="show_forum_json"),
    path('comments/json/', show_comments_json, name="show_comments_json"),
    path('show_forum_json_popular_only/', show_forum_json_popular_only, name="show_forum_popular_only"),
    path('book_details/json/<int:id>', book_details, name="book_details"),
]

lembarpena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('registerbook/', include('registerbook.urls')),
    path('checkoutbook/', include('checkoutbook.urls')),
    path('bookforum/', include('bookforum.urls')),
    path('buybooks/', include('buybooks.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('landing-page/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('login/', login_user, name='login'),
    path('signup/', signup, name='signup'),
    path('landingpageafterlogin/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('logout/', logout_user, name='logout'),
    path('get-user/', get_user_json, name='get_user_json'),
]

bookforum/models.py
from django.db import models
from registerbook.models import Book
from django.contrib.auth.models import User
# Create your models here.
class ForumHead(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    book = models.ForeignKey(Book, on_delete=models.CASCADE, blank=True, null=True)
    date = models.DateField(null=True)
    title = models.CharField(max_length=100)
    question = models.TextField()
    
class ForumComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)
    comment_to = models.ForeignKey(ForumHead, on_delete=models.CASCADE,)
    date = models.DateField(null=True)
    answer = models.TextField()

bookforum/forms.py
from django.forms import ModelForm
from bookforum.models import ForumHead, ForumComment

class FormPertanyaan(ModelForm):
    class Meta:
        model = ForumHead
        fields = ["title", "book", "question", ]


class FormJawaban(ModelForm):
    class Meta:
        model = ForumComment
        fields = ["answer"]

bookforum/views.py
from django.http import HttpResponse, JsonResponse
from bookforum.models import ForumHead, ForumComment
from django.shortcuts import render, redirect, get_object_or_404
import datetime
from datetime import datetime
from django.core import serializers
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages  
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponseNotFound
from registerbook.models import Book
import json
#IMPORT BUAT USER PURA PURAAN
from django.contrib.auth.models import User
# USER_BARU = User(id = 1 , pk = 1, username="Bryan")
# USER_BARU.save()
# Create your views here.
@login_required(login_url='/login/')
def show_forum(request):
    questions = ForumHead.objects.all()
    comments = ForumComment.objects.all()
    last_login = request.COOKIES['last_login']
    parsed_date_time = datetime.strptime(last_login, '%Y-%m-%d %H:%M:%S.%f')
    formatted_without_ms = parsed_date_time.strftime('%Y-%m-%d %H:%M:%S')
    context = {
        'user' : request.user,
        'name':request.user.username,
        'questions' : questions,
        'comments': comments,
        'last_login': formatted_without_ms,
    }
    return render(request, "forum.html", context)

@login_required(login_url='/login/')
@csrf_exempt
def create_question(request):
    if request.method == 'POST':
        user = request.user
        book_id = request.POST.get('book_id')
        book = Book.objects.get(pk=book_id)
        question = request.POST.get('question')
        date = datetime.now()
        title = request.POST.get('title')
        new_question = ForumHead(user = user, book = book, date = date , title = title, question = question)
        # result = {
        #     'pk' : new_question.pk,
        #     'fields' : {
        #         'username' : new_question.user.username,
        #         'title' : new_question.title,
        #         'question' : new_question.question,
        #         'date' : new_question.date,
        #         'book' : new_question.book.title,
        #         'book_id' : new_question.book,
        #     }
        # }
        new_question.save()
        # return JsonResponse(result)
    return HttpResponseNotFound()

@login_required(login_url='/login/')
@csrf_exempt
def create_question_flutter(request):
    if request.method == 'POST':
        user = request.user
        # user = USER_BARU
        data = json.loads(request.body)
        book_id = data['book_id']
        book = Book.objects.get(pk=book_id)
        question = data['question']
        date = datetime.now()
        title = data['title']
        new_question = ForumHead(user = user, book = book, date = date , title = title, question = question)
        # result = {
        #     'pk' : new_question.pk,
        #     'fields' : {
        #         'username' : new_question.user.username,
        #         'title' : new_question.title,
        #         'question' : new_question.question,
        #         'date' : new_question.date,
        #         'book' : new_question.book.title,
        #         'book_id' : new_question.book,
        #     }
        # }
        new_question.save()
        return JsonResponse({"status": "success"}, status=200)
    return JsonResponse({"status": "error"}, status=401)


@login_required(login_url='/login/')
@csrf_exempt
def create_comments(request, pk):
    forum_head = ForumHead.objects.get(pk = pk)
    if request.method == 'POST':
        user = request.user
        # user = USER_BARU
        date = datetime.now()
        answer = request.POST.get('answer')
        new_comment = ForumComment(user = user, comment_to = forum_head, date = date, answer = answer)
        result = {
            'pk' : new_comment.pk,
            'fields' : {
                'username' : new_comment.user.username,
                'comment' : new_comment.answer,
                'date' : new_comment.date
            }
        }
        new_comment.save()
        return JsonResponse(result)
    return HttpResponseNotFound()

@login_required(login_url='/login/')
@csrf_exempt
def create_comments_flutter(request, pk):
    if request.method == 'POST':
        forum_head = ForumHead.objects.get(pk = pk)
        data = json.loads(request.body)
        user = request.user
        date = datetime.now()
        new_comment = ForumComment(user = user, comment_to = forum_head, date = date, answer = data["answer"])
        new_comment.save()

        return JsonResponse({"status": "success"}, status=200)

        # return JsonResponse(result)
    return JsonResponse({"status": "error"}, status=401)
# @login_required(login_url='/login/')
# @csrf_exempt
# def create_comments_flutter(request, id):
#     if request.method == 'POST':
#         forum_head = ForumHead.objects.get(pk = pk)

#         data = json.loads(request.body)

#         new_product = Product.objects.create(
#             user = request.user,
#             name = data["name"],
#             price = int(data["price"]),
#             description = data["description"],
#             categories = data["categories"]
#         )

#         new_product.save()

#         return JsonResponse({"status": "success"}, status=200)
#     else:
#         return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='/login/')
@csrf_exempt
def delete_question(request, username, id):
    if request.method == 'GET' and request.user.username == username:
        ForumHead.objects.get(pk = id).delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login/')
@csrf_exempt
def delete_question_flutter(request, username, id):
    if request.method == 'POST' and request.user.username == username:
        ForumHead.objects.get(pk = id).delete()
        return JsonResponse({'status': 'success'}, status=200)
    return JsonResponse({'status': 'failed'}, status=300)

@login_required(login_url='/login/')
@csrf_exempt
def delete_comments(request, username, id):
    if request.method == 'GET' and request.user.username == username:
        ForumComment.objects.get(pk = id).delete()
        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

@login_required(login_url='/login/')
@csrf_exempt
def delete_comments_flutter(request, username, id):
    if request.method == 'POST' and request.user.username == username :
        ForumComment.objects.get(pk = id).delete()
        return JsonResponse({'status': 'success'}, status=200)
    return JsonResponse({'status': 'failed'}, status=300)

def show_forum_json_2(request):
    data = ForumHead.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')


def show_forum_json(request):
    models = ForumHead.objects.all()
    serialized_data = []
    for model in models:
        connected_comments = ForumComment.objects.filter(comment_to = model)
        comment_counts = len(connected_comments)
        book = model.book
        user = model.user
        model_data = {
            "model": "bookforum.forumhead",
            "pk": model.pk,  # Include the "pk" field
            "fields": {
                "book": book.title,
                "book_id" : book.id,
                "user": user.username,
                "date": str(model.date),  # Convert the date to a string
                "title": model.title,
                "question": model.question,
                "comment_counts" : comment_counts,
                'owned_by_current_user': user.username == request.user.username,
            }
        }
        serialized_data.append(model_data)
        # abis udah append ke serialized_data
    json_data = json.dumps(serialized_data)
    return HttpResponse(json_data, content_type="application/json")

def show_forum_json_popular_only(request):
    models = ForumHead.objects.filter(book__rating__gt=4.5)
    serialized_data = []
    for model in models:
        book = model.book
        connected_comments = ForumComment.objects.filter(comment_to = model)
        comment_counts = len(connected_comments)
        user = model.user
        model_data = {
            "model": "bookforum.forumhead",
            "pk": model.pk,  # Include the "pk" field
            "fields": {
                "book": book.title,
                "book_id" : book.id,
                "user": user.username,
                "date": str(model.date),  # Convert the date to a string
                "title": model.title,
                "question": model.question,
                "comment_counts" : comment_counts,
                'owned_by_current_user': user.username == request.user.username,

            }
        }

        serialized_data.append(model_data)
        # abis udah append ke serialized_data
    json_data = json.dumps(serialized_data)
    return HttpResponse(json_data, content_type="application/json")

def show_comments_json(request):
    data = ForumComment.objects.all()
    return HttpResponse(serializers.serialize('json', data), content_type='application/json')

def show_uniquecomments_json(request, id):
    question = ForumHead.objects.get(pk = id)
    comments = ForumComment.objects.filter(comment_to=question)
    serialized_data = []
    for model in comments:
        user = model.user
        model_data = {
            "model": "bookforum.forumcomment",
            "pk": model.pk,  # Include the "pk" field
            "fields": {
                "user": user.username,
                "comment_to": model.comment_to.pk,
                "date": str(model.date),  # Convert the date to a string
                "answer" :  model.answer,
                'owned_by_current_user': user.username == request.user.username,
            }
        }
        serialized_data.append(model_data)
        # abis udah append ke serialized_data

bookforum/templates/forum.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'Style/forum.css' %}">
<div id="my-data" data-forum-url="{% url 'bookforum:show_forum_json' %}" 
    data-popular-forum-url="{% url 'bookforum:show_forum_popular_only' %}" 
    data-buku="{% url 'bookforum:show_books_json' %}"
    database-url="{% url 'bookforum:show_forumcomments' id_head=9999 %}"
    create-question = "{% url 'bookforum:create_question' %}">
</div>
{% include "navbarloggedin.html" %}
<h2 style="margin: 30px 30px 5px 30px; text-align: center;">Forum Buku</h2>
<div class="d-flex justify-content-center set-margin">
    <a>    
        <button type="button" class="btn btn-primary btn-custom" data-bs-toggle="modal" data-bs-target="#exampleModal" style="background-color: #273faa;">
            Buat Forum Baru
        </button>
    </a>    
</div>

<div class="form-check form-switch form-check-reverse" style="margin: 40px 40px 0px 0px;">
    <input class="form-check-input" type="checkbox" id="flexSwitchCheckReverse">
    <label class="form-check-label" for="flexSwitchCheckReverse" style="font-size: 12px;">Tampilkan hanya diskusi buku dengan rating >4.5</label>
</div>

<table class="row" id="forum_container" style="margin: 0px 40px 40px 40px;"></table>

<!-- Modal untuk melakukan input -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Ayo mulai diskusi!</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="col-form-label">Tentukan Topik:</label>
                        <input type="text" class="form-control" id="title" name="title"></input>
                    </div>
                    <div class="mb-3">
                        <label for="title" class="col-form-label">Pilih Buku:</label>
                        <input type="hidden" id="book_id" name="book_id">
                        <div class="dropdown">
                            <button class="btn btn-secondary dropdown-toggle" id="dropdown-buku" type="button" data-bs-toggle="dropdown" aria-expanded="false" style="max-width: 100%; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                                Pilih buku
                            </button>
                            <ul class="dropdown-menu">
                                <div data-bs-spy="scroll" data-bs-target="#list-example" data-bs-smooth-scroll="true" class="scrollspy-example" tabindex="0">
                                    <div class="list-group">
                                    </div>
                                </ul>
                        </div>
                    </div>
                    <div class="mb-3">
                        <label for="question" class="col-form-label">Silakan masukkan pertanyaan Anda:</label>
                        <textarea class="form-control" id="question" name="question"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Tambahkan Forum</button>
            </div>
        </div>
    </div>
</div>

{% include "footer.html" %}
<script src="{% static 'Script/forum.js' %}"></script>
{% endblock content %}

bookforum/templates/forumcomments.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'Style/forumcomments.css' %}">

{% include "navbarloggedin.html" %}

<div class="container" style="margin-top: 40px;">
    <a href="{% url 'bookforum:show_forum' %}">
        <button type="button" class="btn btn-outline-primary btn-sm" style="margin-bottom: 10px;">←</button>
    </a>
    <div class="row">
        <div class="col-12 col-md-4 forum-question overflow-control-card">
            <h1>Forum Question</h1>
            <div class="forum-question-details">
                <p class="wrap"><strong>Title:</strong> {{ question.title }}</p>
                <p><strong>Date:</strong> {{ question.date }}</p>
                <p><strong>Sender:</strong> {{ question.user }}</p>
            </div>
            <div class="forum-question-body">
                <p class="wrap"><strong>Question:</strong> 
                    {{ question.question }}</p>
                        
            </div>
        </div>
        <div class="col-12 col-md-8 cards">
            <div class="card h-100">
                <div class="card-body ">
                    <h5 class="card-title">{{ question.book.title }}</h5>
                    <p class="card-text line-spaced"></p>
                    <p class="card-text line-spaced"><strong>Author:</strong> {{ question.book.author }}</p>
                    <p class="card-text line-spaced"></p><strong> Rating:</strong> {{ question.book.rating }} </p>
                    <p class="card-text line-spaced"><strong> Voters:</strong> {{ question.book.voters }} </p>
                    <p class="card-text line-spaced"><strong>Price:</strong> {{ question.book.price }} {{question.book.currency}} </p>
                    <p class="card-text line-spaced"><strong>Publisher:</strong> {{ question.book.publisher }}</p>
                    <p class="card-text line-spaced"><strong>Page Count:</strong> {{ question.book.page_count }} </p>
                    <p class="card-text line-spaced"><strong>Genres:</strong> {{ question.book.genres }}</p>
                    <p class="card-text line-spaced"> 
                    <strong>Description:</strong>
                    <p class="card-text line-spaced" style="font-size: medium;"> {{ question.book.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="d-flex flex-row set-margin mb-3">
    <h2 style="margin:20px">Comments</h2>
    <button type="button" class="btn btn-primary btn-custom" data-bs-toggle="modal" data-bs-target="#exampleModal" style="margin: 10px;">
        Tambahkan Tanggapan Anda
    </button>
</div>
<div class="comment-list" id="list-komentar">
    {% for comment in comments %}
    {% empty %}
    <li class="no-comments">No comments yet.</li>
    {% endfor %}
</div>
</div>
<div class="save-url" data-url="{% url 'bookforum:show_uniquecomments_json' question.pk %}" id="url-unique-json"></div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Forum lembarpena</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" data-url="{% url 'bookforum:create_comments' question.pk %}" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="answer" class="col-form-label">Silakan masukkan tanggapan Anda:</label>
                        <textarea class="form-control" id="answer" name="answer"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Tambahkan</button>
            </div>
        </div>
    </div>
</div>
{%include "footer.html" %}
<script src="{% static 'Script/forumcomments.js' %}"></script>
{% endblock content %}