checkoutbook/urls.py
from django.urls import path
from checkoutbook.views import *

app_name = 'checkoutbook'

urlpatterns = [
    path('', show_checkout, name='checkout'),
    path('show_checkout_json/<str:username>/', show_checkout_json, name='show_checkout_json'),
    path('get_total_harga/<str:username>/', get_total_harga, name='get_total_harga'),
    path('checkout_ajax/', checkout_ajax, name='checkout_ajax'),
    path('checkout_flutter/', checkout_flutter, name='checkout_flutter'),
    path('myorder/', show_myorder, name="myorder"),
    path('get_order_json/', get_order_json, name="get_order_json"),
    path('get_order_json_all/', get_order_json_all, name="get_order_json_all"),
    path('get_order_json_cc/', get_order_json_cc, name="get_order_json_cc"),
    path('get_order_json_dc/', get_order_json_dc, name="get_order_json_dc"),
    path('get_order_json_tf/', get_order_json_tf, name="get_order_json_tf"),
    path('get_order_json_ew/', get_order_json_ew, name="get_order_json_ew"),
]

lembarpena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('registerbook/', include('registerbook.urls')),
    path('checkoutbook/', include('checkoutbook.urls')),
    path('bookforum/', include('bookforum.urls')),
    path('buybooks/', include('buybooks.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('landing-page/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('login/', login_user, name='login'),
    path('signup/', signup, name='signup'),
    path('landingpageafterlogin/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('logout/', logout_user, name='logout'),
    path('get-user/', get_user_json, name='get_user_json'),
]

checkoutbook/models.py
from django.db import models
from django.contrib.auth.models import User
from buybooks.models import CartItem

class Checkout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    items = models.ManyToManyField(CartItem)
    alamat = models.TextField()
    metode_pembayaran = models.CharField(max_length=50)
    total_price = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.user.username}'s checkout"

checkoutbook/forms.py
from django import forms
from .models import Checkout

class CheckoutForm(forms.Form):
    class Meta:
        model = Checkout
        fields = ["alamat", "metode_pembayaran"]

checkoutbook/views.py
import json
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponse, JsonResponse
from django.urls import reverse
from django.core import serializers
from .models import CartItem, Checkout
from registerbook.models import Notification
from .forms import CheckoutForm
from django.contrib.auth.decorators import login_required
import datetime
from datetime import datetime
from django.views.decorators.csrf import csrf_exempt



@login_required(login_url='/login')
def show_checkout(request):
    form = CheckoutForm()
    cart_items = CartItem.objects.filter(user=request.user, is_ordered=True)
    total_price = sum(item.subtotal() for item in cart_items)
    last_login = request.COOKIES['last_login']
    parsed_date_time = datetime.strptime(last_login, '%Y-%m-%d %H:%M:%S.%f')
    formatted_without_ms = parsed_date_time.strftime('%Y-%m-%d %H:%M:%S')
    context = {
        'cart_items': cart_items, 
        'total_price': total_price,
        'last_login' : formatted_without_ms,
        'form': form,
        'currency' : 'SAR',
    }
    return render(request, 'checkout.html', context)

def show_checkout_json(request, username):
    # print("a")
    cart_items = CartItem.objects.filter(user__username = username, is_ordered=True)
    cart_data = [
        {
            'id': item.id,
            'title': item.book.title,
            'quantity': item.quantity,
            'subtotal': item.subtotal(),
            'currency': item.book.currency,
            'is_ordered' : item.is_ordered,
        }
        for item in cart_items
    ]

    return JsonResponse(cart_data, safe=False)

def get_total_harga(request, username):
    cart_items = CartItem.objects.filter(user__username = username, is_ordered=True)
    total_price = sum(item.subtotal() for item in cart_items)
    context = [{
        'total_harga' : total_price,
    }]
    return JsonResponse(context, safe=False)


@csrf_exempt
def checkout_ajax(request):
    try:
        if request.method == 'POST':
            user = request.user
            items = CartItem.objects.filter(user=request.user, is_ordered=True)
            alamat = request.POST.get("alamat")
            metode_pembayaran = request.POST.get("metode_pembayaran")

            total_price = sum(item.subtotal() for item in items)
            new_item = Checkout(
                            user=user, 
                            alamat=alamat, 
                            metode_pembayaran=metode_pembayaran, 
                            total_price=total_price
                        )
            
            new_item.save()
            new_item.items.set(items)
            new_item.save()
            
            message = f"Pesanan masuk dari {user.username}.\n"
            message += f"{new_item.alamat} | {new_item.metode_pembayaran} | SAR {new_item.total_price}\n"
            message += "\nOrder Summary:\n"
            for item in items:
                message += f"- {item.book.title}\n"
                
            Notification.objects.create(buyer=user, message=message)
            for item in items:
                item.delete()

            return HttpResponseRedirect(reverse('buybooks:show_cart'))
        
        return HttpResponseNotFound()
    except: 
        return JsonResponse({"user" : user, 
                             "items" : items, 
                             "alamat" : alamat, 
                             "metode_pembayaran" : metode_pembayaran,
                             "total_price" : total_price,
                             "new_item" : new_item})

@login_required
@csrf_exempt
def checkout_flutter(request):
    if request.method == 'POST':
        user = request.user
        items = CartItem.objects.filter(user=request.user, is_ordered=True)

        data = json.loads(request.body)
        alamat = data["alamat"]
        metode_pembayaran = data["metode_pembayaran"]
        total_price = float(data["total_harga"])
        new_item = Checkout(
                        user=user, 
                        alamat=alamat, 
                        metode_pembayaran=metode_pembayaran, 
                        total_price=total_price
                    )
        
        new_item.save()
        new_item.items.set(items)
        new_item.save()
        
        message = f"Pesanan masuk dari {user.username}.\n"
        message += f"{new_item.alamat} | {new_item.metode_pembayaran} | SAR {new_item.total_price}\n"
        message += "\nOrder Summary:\n"
        for item in items:
            message += f"- {item.book.title}\n"
            
        Notification.objects.create(buyer=user, message=message)
        for item in items:
            item.delete()
        return JsonResponse({"status": "success"}, status=200)
    return JsonResponse({"status": "error"}, status=401)

@login_required(login_url='/login')
def show_myorder(request):
    orders = Checkout.objects.filter(user = request.user)
    last_login = request.COOKIES['last_login']
    parsed_date_time = datetime.strptime(last_login, '%Y-%m-%d %H:%M:%S.%f')
    formatted_without_ms = parsed_date_time.strftime('%Y-%m-%d %H:%M:%S')

    context = {
        'orders': orders,
        'last_login' : formatted_without_ms,

    }
    return render(request, 'myorder.html', context)

def get_order_json(request):
    orders = Checkout.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', orders))

def get_order_json_all(request):
    orders = Checkout.objects.all()
    order_data = [
        {
            'model' : "checkoutbook.checkout",
            'pk' : order.pk,
            'fields' : {
                'user': order.user.username,
                'alamat' : order.alamat,
                'metode_pembayaran': order.metode_pembayaran,
                'total_price' : order.total_price,
            }
        }
        for order in orders
    ]
    json_data = json.dumps(order_data)
    return HttpResponse(json_data, content_type="application/json")

def get_order_json_cc(request):
    orders = Checkout.objects.filter(user=request.user, metode_pembayaran="kartu_kredit")
    return HttpResponse(serializers.serialize('json', orders), content_type="application/json")

def get_order_json_dc(request):
    orders = Checkout.objects.filter(user=request.user, metode_pembayaran="kartu_debit")
    return HttpResponse(serializers.serialize('json', orders), content_type="application/json")

def get_order_json_tf(request):
    orders = Checkout.objects.filter(user=request.user, metode_pembayaran="transfer_bank")
    return HttpResponse(serializers.serialize('json', orders), content_type="application/json")

def get_order_json_ew(request):
    orders = Checkout.objects.filter(user=request.user, metode_pembayaran="e_wallet")
    return HttpResponse(serializers.serialize('json', orders), content_type="application/json")

checkoutbook/templates/checkout.html
{% extends 'base.html' %}
<head>
    {% block meta %}
        <title>Checkout</title>
    {% endblock meta %}
</head>

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Style/checkout.css' %}">

<div id="my-data" data-checkout-url="{% url 'checkoutbook:checkout_ajax' %}"></div>

<body>
    <h1 class="text-center">Checkout</h1>
    <table class="table table-bordered" style="align-items: center; text-align: center;">
        <thead>
            <tr>
                <th>Produk</th>
                <th>Harga Satuan</th>
                <th>Jumlah</th>
                <th>Subtotal Harga</th>
            </tr>
        </thead>
        <tbody>
            {% for product in cart_items %}
            <tr>
                <td>{{product.book.title}}</td>
                <td>{{product.book.currency}} {{product.book.price}}</td>
                <td>{{product.quantity}}</td>
                <td>{{product.subtotal}}</td>
            </tr>
            {% endfor %}
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td><h6>Total Harga: {{ currency }} {{ total_price }}</h6></td>
            </tr>
        </tbody>
    </table>
    <form method="post" id="checkout-form" style="text-align: center;">
        {% csrf_token %}
        <div class="mb-3">
            <label for="alamat" class="col-form-label">Alamat:</label>
            <div style="text-align: center;">
            <textarea class="form-control" id="alamat" name="alamat"  style="margin: 0 auto; width: 400px; height: 90px;"></textarea>
            </div>
        </div>
        <div class="mb-3">
            <label for="metode_pembayaran" class="col-form-label">Metode Pembayaran:</label>
            <div>
                <input type="radio" id="metode1" name="metode_pembayaran" value="Kartu Kredit">
                <label for="metode1">Kartu Kredit</label>
            </div>
            <div>
                <input type="radio" id="metode2" name="metode_pembayaran" value="Kartu Debit">
                <label for="metode2">Kartu Debit</label>
            </div>
            <div>
                <input type="radio" id="metode3" name="metode_pembayaran" value="Transfer Bank">
                <label for="metode3">Transfer Bank</label>
            </div>
            <div>
                <input type="radio" id="metode4" name="metode_pembayaran" value="E-Wallet">
                <label for="metode4">E-Wallet</label>
            </div>
        </div>
    </form>
    <div style="text-align: center;">
        <button type="button" class="btn btn-primary" id="button_checkout" style="margin-left: 20px; width: 200px;">Checkout</button>
    </div>  
    <script src="{% static 'Script/checkout.js' %}"></script>  
</body>
{% include "footer.html" %}

{% endblock content %}

checkoutbook/templates/myorder.html
{% extends 'base.html' %}
<head>
    {% block meta %}
        <title>My Order</title>
    {% endblock meta %}
</head>

{% block content %}
{% load static %}
<link rel="stylesheet" href="{% static 'Style/myorder.css' %}">

<div id="my-data" data-order-url="{% url 'checkoutbook:get_order_json' %}" 
    data-order-cc-url="{% url 'checkoutbook:get_order_json_cc' %}"
    data-order-dc-url="{% url 'checkoutbook:get_order_json_dc' %}"
    data-order-tf-url="{% url 'checkoutbook:get_order_json_tf' %}"
    data-order-ew-url="{% url 'checkoutbook:get_order_json_ew' %}">
</div>

{% include "navbarloggedin.html" %}
<div class="container mt-5">
    <h1 style="display: inline;">My Order</h1>
    <label style="display: inline;">Filter: </label>
    <select id="myDropdown" style="display: inline;">
        <option value="all">Semua</option>
        <option value="cc">Metode Pembayaran Kartu Kredit</option>
        <option value="dc">Metode Pembayaran Kartu Debit</option>
        <option value="tf">Metode Pembayaran Transfer Bank</option>
        <option value="ew">Metode Pembayaran E-Wallet</option>
    </select>
    
    <div class="row" id="tempatcard"></div>

</div>
{% include "footer.html" %}
<script src="{% static 'Script/myorder.js' %}"></script>
{% endblock %}