lembarpena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('registerbook/', include('registerbook.urls')),
    path('checkoutbook/', include('checkoutbook.urls')),
    path('bookforum/', include('bookforum.urls')),
    path('buybooks/', include('buybooks.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('landing-page/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('login/', login_user, name='login'),
    path('signup/', signup, name='signup'),
    path('landingpageafterlogin/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('logout/', logout_user, name='logout'),
    path('get-user/', get_user_json, name='get_user_json'),
]

registerbook/urls.py
from django.urls import path
from registerbook.views import (show_registered_books, show_received_orders, show_json, 
                                show_json_by_id, get_book_json, add_book_ajax, remove_book, 
                                mark_notification_read, remove_notification, get_notif_json, 
                                create_book_flutter, mark_all_notifications_read)

app_name = 'registerbook'

urlpatterns = [
    path('', show_registered_books, name='show_registered_books'),
    path('received-orders/', show_received_orders, name='show_received_orders'),
    path('json/', show_json, name='show_json'),
    path('json/<int:id>/', show_json_by_id, name='show_json_by_id'),
    path('get-book/', get_book_json, name='get_book_json'),
    path('get-notif/', get_notif_json, name='get_notif_json'),
    path('add-book-ajax/', add_book_ajax, name='add_book_ajax'),
    path('delete-book-ajax/<int:book_id>/', remove_book, name='remove_book'),
    path('delete-notification/<int:notif_id>/', remove_notification, name='remove_notification'),
    path('mark-notification-read/<int:notif_id>/', mark_notification_read, name='mark_notification_read'),
    path('mark-all-notifications-read/', mark_all_notifications_read, name='mark_all_notifications_read'),
    path('create-book-flutter/', create_book_flutter, name='create_book_flutter'),
]

registerbook/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    rating = models.DecimalField(max_digits=3, decimal_places=1)
    voters = models.IntegerField()
    price = models.DecimalField(max_digits=6, decimal_places=2)
    currency = models.CharField(max_length=20)
    description = models.TextField()
    publisher = models.CharField(max_length=300)
    page_count = models.IntegerField()
    genres = models.CharField(max_length=200)
    # user = models.ForeignKey(User, on_delete=models.CASCADE,)

    def __str__(self):
        return self.title
    
class Notification(models.Model):
    buyer = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
    is_read = models.BooleanField(default=False)
    timestamp = models.DateTimeField(auto_now_add=True)

registerbook/forms.py
from django.forms import ModelForm
from registerbook.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ["title", "author", "rating", 
                  "voters", "price", "currency", 
                  "publisher", "page_count", 
                  "genres", "description"]

registerbook/views.py
import json
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse, HttpResponseNotAllowed, HttpResponseNotFound, JsonResponse
from django.core import serializers
from .models import Book
from datetime import datetime
from .models import Notification


@login_required(login_url='/login')
def show_registered_books(request):
    books = Book.objects.all()
    
    last_login = request.COOKIES['last_login']
    parsed_date_time = datetime.strptime(last_login, '%Y-%m-%d %H:%M:%S.%f')
    formatted_without_ms = parsed_date_time.strftime('%Y-%m-%d %H:%M:%S')
    context = {
        'last_login' : formatted_without_ms,
        'username': request.user,
        'books': books,
    }

    return render(request, 'regist_book.html', context)

@login_required(login_url='/login')
def show_received_orders(request):
    last_login = request.COOKIES.get('last_login')
    if last_login:
        parsed_date_time = datetime.strptime(last_login, '%Y-%m-%d %H:%M:%S.%f')
        formatted_without_ms = parsed_date_time.strftime('%Y-%m-%d %H:%M:%S')
    else:
        formatted_without_ms = ""

    notifications = Notification.objects.all().order_by('-timestamp')

    context = {
        'username': request.user,
        'notifications': notifications,
        'last_login' : formatted_without_ms,
    }

    return render(request, 'received_orders.html', context)

def show_json(request):
    books = Book.objects.all()
    return HttpResponse(serializers.serialize('json', books), content_type="application/json")

def show_json_by_id(request, id):
    data = Book.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def get_book_json(request):
    rating_filter = request.GET.get('rating_filter')
    
    if rating_filter == "gt4":
        books = Book.objects.filter(rating__gt=4)
    elif rating_filter == "lte4":
        books = Book.objects.filter(rating__lte=4)
    else:
        books = Book.objects.all()
        
    return HttpResponse(serializers.serialize('json', books))

def get_notif_json(request):
    notif = Notification.objects.all()
    return HttpResponse(serializers.serialize('json', notif))

@csrf_exempt
def add_book_ajax(request):
    if request.method == 'POST':
        title = request.POST.get("title")
        author = request.POST.get("author")
        rating = float(request.POST.get("rating"))
        voters = int(request.POST.get("voters"))
        price = float(request.POST.get("price"))
        currency = request.POST.get("currency")
        description = request.POST.get("description")
        publisher = request.POST.get("publisher")
        page_count = int(request.POST.get("page_count"))
        genres = request.POST.get("genres")

        new_book = Book(
            title=title, 
            author=author, 
            rating=rating,
            voters=voters, 
            price=price, 
            currency=currency,
            description=description, 
            publisher=publisher,
            page_count=page_count, 
            genres=genres,
        )
        new_book.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

@csrf_exempt
def create_book_flutter(request):
    if request.method == 'POST':  
        data = json.loads(request.body)

        new_book = Book.objects.create(
            title = data["title"],
            author = data["author"],
            rating = float(data["rating"]),
            voters = int(data["voters"]),
            price = float(data["price"]),
            currency = data["currency"],
            description = data["description"],
            publisher = data["publisher"],
            page_count = int(data["page_count"]),
            genres = data["genres"],
        )
        new_book.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def remove_book(request, book_id):
    if request.method == "DELETE":
        try:
            book = Book.objects.get(pk=book_id)
            book.delete()
            return JsonResponse({"status": "success"}, status=200)
        except Book.DoesNotExist:
            return JsonResponse({"status": "failed", "error": "Book not found"}, status=404)
    return HttpResponseNotAllowed(['DELETE'])

@csrf_exempt
def mark_notification_read(request, notif_id):
    try:
        notif = Notification.objects.get(pk=notif_id)
        notif.is_read = True
        notif.save()
        return JsonResponse({"status": "success"}, status=200)
    except Notification.DoesNotExist:
        return JsonResponse({"status": "failed", "error": "Notification not found"}, status=404)

@csrf_exempt
def remove_notification(request, notif_id):
    if request.method == "DELETE":
        try:
            notif = Notification.objects.get(pk=notif_id)
            notif.delete()
            return JsonResponse({"status": "success"}, status=200)
        except Notification.DoesNotExist:
            return JsonResponse({"status": "failed", "error": "Notification not found"}, status=404)
    return HttpResponseNotAllowed(['DELETE'])

@login_required(login_url='/login')
@csrf_exempt
def mark_all_notifications_read(request):
    Notification.objects.filter(buyer=request.user).update(is_read=True)
    return JsonResponse({"status": "success"}, status=200)

registerbook/templates/navbarseller.html
<style>
    .body{
        font-family: 'Poppins', sans-serif;
    }

    a{
        font-family: 'Poppins', sans-serif;
    }

    .navbar a:hover {
      color: #273faa; 
    }
    #log-out {
      color: #273faa; 
      border-color: #273faa; 
      background-color: transparent; 
    }
    #log-out:hover {
      color: #ffffff;
      background-color: #273faa; 
    }
  </style>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'main:show_landing_page' %}">Lembar Pena - Hi, {{user.username}}!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          </ul>
          <a class="nav-link active" href="{% url 'registerbook:show_registered_books' %}" style="margin-right: 30px;">Your Books</a>
          <a class="nav-link active" href="{% url 'registerbook:show_received_orders' %}" style="margin-right: 30px;">Received Order</a>
          <a class="btn btn-outline-success" id="log-out" style="margin-right: 10px;" href="{% url 'main:logout' %}">Logout</a>    
      </div>
  </nav>

  

registerbook/templates/received_orders.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
  <title>Received Orders</title>
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'Style/received_orders.css' %}">
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/js/bootstrap.min.js"></script>
{% endblock meta %}

{% block content %}
<div id="data-urls" 
     data-mark-notification-read-url="/registerbook/mark-notification-read/"
     data-delete-notification-url="/registerbook/delete-notification/">
</div>

{% include "navbarseller.html" %}
  <div class="container">
    <div class="notificationContainer">
      <header class="d-flex justify-content-between align-items-center mb-3">
        <div class="d-flex align-items-center">
            <h1 class="mr-2">Order Notification</h1>
            <span id="num-of-notif"></span>
        </div>
        <p id="mark-as-read">Mark as All Read</p>
      </header>
      <main>
        {% for notif in notifications %}
        <div class="card mb-3 {% if not notif.is_read %}border-primary{% endif %}">
            <div class="card-body">
                <img alt="photo" src="{% static 'Gambar/profile.png' %}" class="float-left mr-3" style="width: 50px; height: 50px; border-radius: 50%;">
                {% autoescape off %}
                {{ notif.message|linebreaks }}
                {% endautoescape %}
                <button class="btn btn-sm btn-info float-right" data-notif-id="{{ notif.id }}">Read</button>
                <button class="btn btn-sm btn-danger float-right mr-2 delete-notif-btn" data-notif-id="{{ notif.id }}">Delete</button>
            </div>
        </div>
        {% endfor %}
      </main>
    </div>
  </div>

<script src="{% static 'Script/received_orders.js' %}"></script>

{% include "footer.html" %}
{% endblock %}

registerbook/templates/regist_book.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}

    <title>Seller Page</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'Style/regist_book.css' %}">
{% endblock meta %}

{% block content %}
<div id="data-urls" 
    data-add-book-ajax-url="{% url 'registerbook:add_book_ajax' %}"
    data-delete-book-ajax-url="delete-book-ajax/"
    data-logout-url="{% url 'main:logout' %}"
    data-get-book-json-url="{% url 'registerbook:get_book_json' %}">
</div>

{% include "navbarseller.html" %}
<div class="tag1"></div>
<div class="container mt-5">
    <h1>Book Collection</h1>
    <div class="mb-3">
        <label for="ratingFilter" class="form-label">Filter by Rating:</label>
        <select id="ratingFilter" class="form-control w-auto">
            <option value="">All Ratings</option>
            <option value="gt4">> 4.0</option>
            <option value="lte4">≤ 4.0</option>
        </select>
    </div>    
    <div class="row card-container align-items-stretch">
        <div id="product_table" class="row"></div>
    </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Add New Book</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form" onsubmit="return false;">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="title" class="col-form-label">Title:</label>
                        <input type="text" class="form-control" id="title" name="title"></input>
                    </div>
                    <div class="mb-3">
                        <label for="author" class="col-form-label">Author:</label>
                        <input type="text" class="form-control" id="author" name="author"></input>
                    </div>
                    <div class="mb-3">
                        <label for="rating" class="col-form-label">Rating:</label>
                        <input type="number" class="form-control" id="rating" name="rating"></input>
                    </div>
                    <div class="mb-3">
                        <label for="voters" class="col-form-label">Voters:</label>
                        <input type="number" class="form-control" id="voters" name="voters"></input>
                    </div>
                    <div class="mb-3">
                        <label for="price" class="col-form-label">Price:</label>
                        <input type="number" class="form-control" id="price" name="price"></input>
                    </div>
                    <div class="mb-3">
                        <label for="currency" class="col-form-label">Currency:</label>
                        <input type="text" class="form-control" id="currency" name="currency"></input>
                    </div>
                    <div class="mb-3">
                        <label for="publisher" class="col-form-label">Publisher:</label>
                        <input type="text" class="form-control" id="publisher" name="publisher"></input>
                    </div>
                    <div class="mb-3">
                        <label for="page_count" class="col-form-label">Page Count:</label>
                        <input type="number" class="form-control" id="page_count" name="page_count"></input>
                    </div>
                    <div class="mb-3">
                        <label for="genres" class="col-form-label">Genres:</label>
                        <input type="text" class="form-control" id="genres" name="genres"></input>
                    </div>
                    <div class="mb-3">
                        <label for="description" class="col-form-label">Description:</label>
                        <textarea class="form-control" id="description" name="description"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary" id="button_add" data-bs-dismiss="modal">Add Book</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="bookDetailModal" tabindex="-1" aria-labelledby="bookDetailLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="bookDetailLabel">Book Description</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="bookDescriptionContent">
                <!-- Description will be filled dynamically here -->
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="d-flex justify-content-center align-items-center" style="height: 10vh;">
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">Add Book</button>
</div>

{% include "footer.html" %}

<script src="{% static 'Script/regist_book.js' %}"></script>

{% endblock %}