bookforum/urls.py
from django.urls import path
from bookforum.views import *

app_name = 'bookforum'

urlpatterns = [
    path('', show_forum, name='show_forum' ),
    path('create_question/', create_question, name='create_question'),
    path('create_question_flutter/', create_question_flutter, name='create_question_flutter'),
    path('create_comments/<int:pk>', create_comments, name="create_comments"),
    path('create_comments_flutter/<int:pk>', create_comments_flutter, name="create_comments_flutter"),
    path('delete_question/<str:username>/<int:id>', delete_question, name="delete_question"),
    path('delete_question_flutter/<str:username>/<int:id>', delete_question_flutter, name="delete_question"),
    path('delete_comments/<str:username>/<int:id>', delete_comments, name="delete_comments"),
    path('delete_comments_flutter/<str:username>/<int:id>', delete_comments_flutter, name="delete_comments_flutter"),
    path('uniquecomments/json/<int:id>', show_uniquecomments_json, name="show_uniquecomments_json"),
    path('show_books_json/json/', show_books_json, name="show_books_json"),
    path('forum/json2/', show_forum_json_2, name="show_forum_json_2"),
    path('show_forumcomments/<int:id_head>/', show_forumcomments, name="show_forumcomments"),
    path('forum/json/', show_forum_json, name="show_forum_json"),
    path('comments/json/', show_comments_json, name="show_comments_json"),
    path('show_forum_json_popular_only/', show_forum_json_popular_only, name="show_forum_popular_only"),
    path('book_details/json/<int:id>', book_details, name="book_details"),
]

buybooks/urls.py
from django.urls import path
from .views import *
app_name = 'buybooks'

urlpatterns = [    
    path('', show_buybooks, name="show_buybooks"),
    path('cart/', show_cart, name="show_cart"),
    path('create/<int:id>/', add_cart_ajax, name="add_cart"),
    path('create-flutter/<int:id>/', add_to_cart, name="add_to_cart"),
    path('delete/<int:id>/', delete_cart, name="delete_cart"),
    path('show_books_json/', show_books_json, name="show_books_json"),
    path('show_books_json_lt', show_books_json_rating_lt, name="show_books_json_lt"),
    path('show_books_json_gte', show_books_json_rating_gte, name="show_books_json_gte"),
    path('selected/<int:id>/', selected, name="selected"),
    path('show_cart_json/<str:uname>/', show_cart_json, name="show_cart_json"),
    path('show_carts_json', show_carts_json, name="show_carts_json"),
    path('delete_cart_flutter/<int:id>/', delete_cart_flutter, name="delete_cart_flutter"),
    path('selected_flutter/<int:id>/', selected_flutter, name="selected_flutter"),
]

checkoutbook/urls.py
from django.urls import path
from checkoutbook.views import *

app_name = 'checkoutbook'

urlpatterns = [
    path('', show_checkout, name='checkout'),
    path('show_checkout_json/<str:username>/', show_checkout_json, name='show_checkout_json'),
    path('get_total_harga/<str:username>/', get_total_harga, name='get_total_harga'),
    path('checkout_ajax/', checkout_ajax, name='checkout_ajax'),
    path('checkout_flutter/', checkout_flutter, name='checkout_flutter'),
    path('myorder/', show_myorder, name="myorder"),
    path('get_order_json/', get_order_json, name="get_order_json"),
    path('get_order_json_all/', get_order_json_all, name="get_order_json_all"),
    path('get_order_json_cc/', get_order_json_cc, name="get_order_json_cc"),
    path('get_order_json_dc/', get_order_json_dc, name="get_order_json_dc"),
    path('get_order_json_tf/', get_order_json_tf, name="get_order_json_tf"),
    path('get_order_json_ew/', get_order_json_ew, name="get_order_json_ew"),
]

lembarpena/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wishlist/', include('wishlist.urls')),
    path('registerbook/', include('registerbook.urls')),
    path('checkoutbook/', include('checkoutbook.urls')),
    path('bookforum/', include('bookforum.urls')),
    path('buybooks/', include('buybooks.urls')),
    path('', include('main.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import *

app_name = 'main'

urlpatterns = [
    path('', show_landing_page, name='show_landing_page'),
    path('landing-page/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('login/', login_user, name='login'),
    path('signup/', signup, name='signup'),
    path('landingpageafterlogin/', show_landing_page_logged_in, name='show_landing_page_logged_in'),
    path('logout/', logout_user, name='logout'),
    path('get-user/', get_user_json, name='get_user_json'),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import *

app_name = 'wishlist'

urlpatterns = [
    path('', mywishlist, name='mywishlist'),    
    path('bookprofile/', show_book_profile, name='bookprofile'),
    path('book/<int:book_id>/', show_book_details, name='show_book_details'),
    path('add_to_wishlist/', add_to_wishlist, name='add_to_wishlist'),
    path('delete_wishlist_item/<int:item_id>/', delete_wishlist_item, name='delete_wishlist_item'),
    path('delete_wishlist_item_flutter/<int:item_id>/', delete_wishlist_item_flutter, name='delete_wishlist_item_flutter'),
    path('get-books/', get_books, name='get_books'),
    path('mywishlist/json', mywishlist_json, name='mywishlist_json'),
    path('add_to_wishlist_flutter/', add_to_wishlist_flutter, name= 'add_to_wishlist_flutter'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1.0"
        />
        {% block meta %}
        {% endblock meta %}
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap" rel="stylesheet">

    </head>

    <body>
        <!-- <style>    
        @font-face {
            font-family: 'Poppins';  
            src: url('/static/Poppins/Poppins-Black.ttf') format('truetype'),
                url('/static/Poppins/Poppins-BlackItalic.ttf') format('truetype'),
                url('/static/Poppins/Poppins-Bold.ttf') format('truetype'),
                url('/static/Poppins/Poppins-BoldItalic.ttf') format('truetype'),
                url('/static/Poppins/Poppins-ExtraBoldItalic.ttf') format('truetype'),
                url('/static/Poppins/Poppins-ExtraBold.ttf') format('truetype'),
                url('/static/Poppins/Poppins-Light.ttf') format('truetype'),
                url('/static/Poppins/Poppins-Medium.ttf') format('truetype'),
                url('/static/Poppins/Poppins-SemiBold.ttf') format('truetype'),
        }
        </style> -->
        {% block content %}
        {% endblock content %}
    </body>
</html>

templates/faq.html
<style>
    .faq{
        display: flex;
        justify-content: center;
        align-items: center;
        width: 60vw;
        margin: 0 auto;
    } 
    .faq-text{
        text-align: center;
        margin: 20px;
    }
</style>
<div class="faq-text"><strong>Frequently Asked Question</strong></div>
    <div class="faq">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Apa itu LembarPena?
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <strong>LembarPena</strong> adalah sebuah aplikasi marketplace belanja buku yang memungkinkan Anda untuk menjelajahi, mencari, dan membeli berbagai jenis buku secara online. Kami menyediakan akses ke koleksi buku yang luas, termasuk buku-buku terbaru, buku terlaris, buku bekas, dan banyak lagi. Dengan LembarPena, Anda dapat dengan mudah menemukan buku-buku favorit Anda dan melakukan pembelian secara praktis melalui aplikasi kami.
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                        Apa itu Fitur Forum Buku di LembarPena?
                    </button>
                </h2>
                <div id="collapseTwo" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <strong>Fitur Forum Buku di LembarPena</strong> adalah wadah interaktif tempat pengguna aplikasi dapat berpartisipasi dalam diskusi, berbagi pendapat, dan berkomunikasi tentang buku. Ini adalah ruang online di mana pembaca, penulis, dan penggemar buku dapat bertukar pikiran, merekomendasikan buku, dan berbicara tentang berbagai aspek buku yang mereka baca.
                    </div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                        Apakah Wishlist Book bersifat pribadi atau dapat dibagikan dengan pengguna lain?
                    </button>
                </h2>
                <div id="collapseThree" class="accordion-collapse collapse" data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <strong>Wishlist Book pada LembarPena</strong> bersifat pribadi secara default. Ini berarti daftar buku yang disimpan hanya dapat diakses oleh pengguna yang menyimpannya.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

templates/footer.html
<link href='https://cdn.jsdelivr.net/npm/boxicons@2.0.5/css/boxicons.min.css' rel='stylesheet'>
<style>   
  .footer {
      background-color: #1C2964;
      color: #fff;
      text-align: center;
      font-weight: 600;
      padding: 2rem 0;
      margin-top: 40px;
  }

  .footer__title {
      font-size: 2rem;
      margin-bottom: 2rem;
  }

  .footer__social {
      margin-bottom: 2rem;
  }

  .footer__icon {
      font-size: 1.5rem;
      color: #fff;
      margin: 0 1rem;
  }
  
  footer ul {
      list-style: none;
      padding: 0;
  }

  footer li {
    display: inline;
    margin: 0 20px;
  }

  footer a {
      text-decoration: none;
      color: #fff;
      font-weight: bold;
  }

  footer a:hover {
    color: #a6b7ef; /* Change color on hover */
  }

  .footer__copy {
      font-size: .75rem;
  }
</style>

<footer class="footer">
  <p class="footer__title">LembarPena</p>
  <div class="footer__social">
      <a href="https://github.com/PBPC09/tugaskelompok1" class="footer__icon"><i class='bx bxl-github'></i></a>
      <a href="#" class="footer__icon"><i class='bx bxl-linkedin'></i></a>
      <a href="#" class="footer__icon"><i class='bx bxl-instagram'></i></a>
  </div>
  <ul>
    <li><a href="#">Home</a></li>
    <li><a href="#">About Us</a></li>
    <li><a href="#">Explore</a></li>
  </ul>
  <p class="footer__copy">&#169; Created by C09</p>  
  {% if user.is_authenticated %}
    <p class="footer__copy">Last Login : {{ user.last_login }}</p>
  {% endif %}
</footer>

templates/navbarloggedin.html
<style>
  *{
    font-family:'Poppins',sans-serif;
  }
  
  .navbar a:hover {
    color: #273faa; 
  }
  #log-out {
    color: #273faa; 
    border-color: #273faa; 
    background-color: transparent; 
  }
  #log-out:hover {
    color: #ffffff;
    background-color: #273faa; 
  }
  * {
    font-family: 'Poppins', sans-serif;
  }
</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'main:show_landing_page_logged_in' %}">Lembar Pena - Hi, {{user.username}}!</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        </ul>
        <a class="nav-link active" href="{% url 'main:show_landing_page_logged_in' %}" style="margin-right: 30px;">Home</a>
        <a class="nav-link active" href="{% url 'wishlist:bookprofile' %}" style="margin-right: 30px;">Explore Book</a>
        <a class="nav-link active" href="{% url 'wishlist:mywishlist' %}" style="margin-right: 30px;">Wishlist</a>
        <a class="nav-link active" href="{% url 'buybooks:show_cart' %}" style="margin-right: 30px;">Cart</a>
        <a class="nav-link active" href="{% url 'buybooks:show_buybooks' %}" style="margin-right: 30px;">Buy Books</a>
        <a class="nav-link active" href="{% url 'bookforum:show_forum' %}" style="margin-right: 30px;">Book Forum</a>
        <a class="nav-link active" href="{% url 'checkoutbook:myorder' %}" style="margin-right: 30px;">My Order</a>
        <a class="btn btn-outline-success" id="log-out" style="margin-right: 10px;" href="{% url 'main:logout' %}">Logout</a>    
    </div>
</nav>

templates/navbarlogin.html
<style>
  .navbar a:hover {
    color: #273faa; 
  }
  #log-in, #sign-up {
    color: #273faa; 
    border-color: #273faa; /* Warna garis tepi tombol */
    background-color: transparent; 
  }
  #log-in:hover, #sign-up:hover {
    color: #ffffff; 
    background-color: #273faa; 
  }
</style>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'main:show_landing_page' %}">Lembar Pena</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarScroll">
            <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
            </ul>
            <a class="btn btn-outline-success button-hover" id="log-in" style="margin-right: 10px;" href="{% url 'main:login' %}">Login</a>
            <a class="btn btn-outline-success button-hover" id="sign-up" href="{% url 'main:signup' %}">Register</a>
        </div>
    </div>
</nav>

templates/navbarseller.html
<style>
    .body{
        font-family: 'Poppins', sans-serif;
    }

    a{
        font-family: 'Poppins', sans-serif;
    }

    .navbar a:hover {
      color: #273faa; 
    }
    #log-out {
      color: #273faa; 
      border-color: #273faa; 
      background-color: transparent; 
    }
    #log-out:hover {
      color: #ffffff;
      background-color: #273faa; 
    }
  </style>
  <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'registerbook:show_registered_books' %}">Lembar Pena - Hi, {{user.username}}!</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          </ul>
          <a class="nav-link active" href="{% url 'registerbook:show_registered_books' %}" style="margin-right: 30px;">Home</a>
          <a class="nav-link active" href="{% url 'registerbook:show_received_orders' %}" style="margin-right: 30px;">Received Order</a>
          <a class="btn btn-outline-success" id="log-out" style="margin-right: 10px;" href="{% url 'main:logout' %}">Logout</a>    
      </div>
  </nav>